POST http://192.168.107.83:8000/auth/users/
Content-Type: application/json

{
    "username": "test44",
    "email": "kyryllebedin@gmail.com",
    "password": "qwerty12345@",
    "re_password": "qwerty12345@"
}


