POST http://127.0.0.1:8000/auth/users/
Content-Type: application/json

{
    "username": "test25",
    "email": "kirtokyni@gmail.com",
    "password": "yourpassword",
    "re_password": "yourpassword"
}


