POST http://192.168.174.203:8000/auth/users/
Content-Type: application/json

{
    "username": "jamwilltim16",
    "email": "jamwillharvey@gmail.com",
    "password": "123",
    "re_password": "123"
}


