GET http://127.0.0.1:8000/game/questions/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMDgxNjcyLCJpYXQiOjE3NDAwNjM2NzIsImp0aSI6IjE4NDY4MWUyYzMzNTRkZWVhYmI4ZGZkN2QwZDRjYWM0IiwidXNlcl9pZCI6MzZ9.xxfzJfqzzg1bCB-UGb3Czhz43RZkjf8SX9ofuAF6oxI
Content-Type: application/json

{
    "category": "Cyber Security",
    "n": 4,
    "hint": true
}


