POST http://127.0.0.1:8000/auth/jwt/refresh
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczOTYzNDU5NiwiaWF0IjoxNzM5NTQ4MTk2LCJqdGkiOiIyODliMTIwNGY1NjE0Mjk2OWNiOTRmNDM5ZTVjNjhiZiIsInVzZXJfaWQiOjMxfQ.-G8rJgzdIHf1YUJmadWdZmaCGDE930tvUiAaS0R7Ta0"
}