# Generated by Django 5.1.6 on 2025-02-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=255)),
                ('incorrect_answer1', models.CharField(max_length=255)),
                ('incorrect_answer2', models.CharField(max_length=255)),
                ('incorrect_answer3', models.CharField(max_length=255)),
            ],
        ),
    ]
