# Generated by Django 5.1.6 on 2025-03-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
